#!/bin/bash
set -e

if ! type -p fzf >/dev/null; then
  echo "error: fzf not found on the system" >&2
  exit 1
fi

version="0.0.1"

repo="$(gh config get -h github.com user)/todo"
if [ -n "$GH_TODO_REPO" ]; then
    repo="$GH_TODO_REPO"
fi

function version {
  echo "gh-todo v.$version"
}

function usage {
  version
  cat << EOS >&2
GitHub CLI extension for managing Todo in GitHub Issues

USAGE:
  gh todo [action] [flag]

ACTIONS:
  add         Add new todo

FLAGS:
  --help      Show this help
  --version   Show version
EOS
}

function invalid {
  usage
  echo
  echo "error: $@" >&2
  exit 1
}

function select_issue {
  local preview_cmd="gh issue view -R $repo --json labels,milestone,createdAt,body --template"
  preview_cmd+=' "CREATED AT: {{.createdAt | timefmt \"2006-01-02 15:04 MST\"}}
MILESTONE : {{and .milestone .milestone.title}}
LABELS    : {{range .labels}}[ {{.name}} ] {{end}}

----

{{.body}}"'
  preview_cmd+=' $(echo {} | cut -d " " -f 1)'

  gh issue list -R $repo --json number,title,updatedAt --template\
    '{{range .}}{{tablerow (printf "#%v" .number | autocolor "green") .title (timeago .updatedAt)}}{{end}}'\
    | fzf --preview "$preview_cmd"
}

function add {
  echo "add"
}

case $1 in
  -v | --version)
    version
    exit 0
    ;;
  -h | --help)
    usage
    exit 0
    ;;
  add)
    shift
    add
    exit 0
    ;;
esac

selected_issue=$(select_issue)
if [[ -z select_issue ]]; then
  exit 0
fi

echo $selected_issue
echo

# 後方最長一致で先頭のissue番号を取り出す
issue_id=$(echo ${selected_issue%% *})

PS3='Please select action: '
select action in "comment" "edit" "done" "view" "browse" "quit"
do
  echo
  case $action in
    comment)
      gh issue comment -R $repo -e $issue_id
      exit 0
      ;;
    edit)
      gh issue edit -R $repo $issue_id
      exit 0
      ;;
    done)
      gh issue close -R $repo $issue_id
      exit 0
      ;;
    view)
      gh issue view -R $repo $issue_id
      exit 0
      ;;
    browse)
      gh issue view -R $repo --web $issue_id
      exit 0
      ;;
    quit)
      exit 0
      ;;
    *)
      echo "error: not valid, input again"
      ;;
  esac
done
