#!/bin/bash
set -e

if ! type -p fzf >/dev/null; then
  echo "error: fzf not found on the system" >&2
  exit 1
fi

version="0.0.1"

repo="$(gh config get -h github.com user)/todo"
if [ -n "$GITHUB_TODO_REPO" ]; then
    repo="$GITHUB_TODO_REPO"
fi

function usage {
  cat << EOS >&2
gh todo
  GitHub CLI extension for managing Todo in GitHub Issues

USAGE:
  gh todo <action> [flag]

ACTIONS:
  add       Add new todo
  edit      Edit todo
  comment   Add a comment to todo
  done      Mark todo as done
  list      Display a list of todo
  view      View todo details
  browse    Open the todo in web browser

FLAGS:
  --help      Show this help
  --version   Show version
EOS
}

function add {
  echo "add"
}

function edit {
  echo "edit"
}

function comment {
  echo "comment"
}

function _done {
  echo "done"
}

function list {
  echo "list"
}

function view {
  echo "view"
}

function browse {
  echo "browse"
}

function invalid {
  usage
  echo
  echo "error: $@" >&2
  exit 1
}

command="$1"

case $command in
  -v | --version)
    echo "gh-todo v.$version"
    exit 0
    ;;
  -h | --help)
    usage
    exit 0
    ;;
  add)
    shift
    add
    ;;
  edit)
    edit
    ;;
  comment)
    comment
    ;;
  done)
    shift
    _done
    ;;
  list)
    list
    ;;
  view)
    shift
    view
    ;;
  browse)
    shift
    browse
    ;;
  *)
    if [[ -n $command ]]; then
      invalid "unknown command or option \"$command\" for \"todo\""
    fi
    usage
    ;;
esac

